### ISSUE TITLE
cme floating-point division

### ISSUE THREAD

**Issue by jerdmann** [Open-Markets-Initiative/wireshark-lua#1]
Hi there!  So I noticed a bug with handling exponent on cme.  The current factor division looks like this:
```
  local factor = 10000000
  return "MD Entry Px: "..value/factor
```
In these cases, `value` is a uint64 extracted from a range in the buffer.  This means the __div metamethod is called which returns an integer result so we lose any decimal places.

https://wiki.wireshark.org/LuaAPI/Int64#Int64.__div.28.29

If we add `:tonumber()`, we get the underlying lua number which means we now show decimals.
```
  local factor = 10000000
  return "MD Entry Px: "..value:tonumber()/factor
```
Thanks for the project, super useful!

**Comment by Open-Markets-Initiative** [comment]
Thanks, I will update and regenerate.  Any chance you have a packet with this field I could test against?  Also, if you have any other suggestions, please let me know.

**Comment by Open-Markets-Initiative** [comment]
I added your update to the model and regenerated. Please take a look.

**Comment by jerdmann** [comment]
Looks great, thanks a ton!  Here's a small pcap snippet with 100 messages from CME's sim environment.  I see some price decimals in the decode now so I think we're good.

[cme.pcap.zip](https://github.com/Open-Markets-Initiative/wireshark-lua/files/2375466/cme.pcap.zip)

**Comment by Open-Markets-Initiative** [comment]
Thanks. Please let me know if you have any other suggestions.  Or need dissectors for other exchange protocols.
