### ISSUE TITLE
Nyse.Equities.ImbalancesFeed.Xdp.v2.1.f.Lua getting error

### ISSUE THREAD

**Issue by sbolberov** [Open-Markets-Initiative/wireshark-lua#11]
I'm getting error while trying to use this LUA.
[timbertrace-2019-50-15_15.50.48.zip](https://github.com/Open-Markets-Initiative/wireshark-lua/files/3521348/timbertrace-2019-50-15_15.50.48.zip)

**Comment by Open-Markets-Initiative** [comment]
The provided capture is likley version 2.2, our latest is version 2.1.  

Please try:

https://github.com/Open-Markets-Initiative/wireshark-lua/blob/master/Nyse/Nyse.Equities.ImbalancesFeed.Xdp.v2.2.a.Script.Dissector.lua

Thanks for the sample. Let us know if you see anything else.
