### ISSUE TITLE
Request to display "null" when fields of type uInt32NULL contain the null value

### ISSUE THREAD

**Issue by hoffmanfpga** [Open-Markets-Initiative/wireshark-lua#13]
Request to display "null" when fields of type uInt32NULL contain the null value. The CME xml says the null value should be 4294967295 (0xffffffff) but according to actual MD captured today I'm seeing the value 2147483647 (0x7fffffff) used for null.

For example, the field Number Of Orders is type uInt32NULL. If the field contain the value 2147483647 (0x7fffffff) then it would be nice if its dissection looked like: `Number Of Orders: null`.

Thanks.

**Comment by Open-Markets-Initiative** [comment]
The sbe loader seems to have several omissions.  There is code to handle nullable types, but not the fields.  Will add also (note it will say: No Value). Thanks

**Comment by Open-Markets-Initiative** [comment]
Please see latest updates.  Let me know if you see anything else.
