### ISSUE TITLE
iLink3 SBE v8.5 dissector "Range is out of bounds" errors

### ISSUE THREAD

**Issue by gburca** [Open-Markets-Initiative/wireshark-lua#19]
2 different `Range is out of bounds` errors in the 2 packets attached. Dissected with dissector in
80865fb14.

[iLink3DissectorErrors.zip](https://github.com/Open-Markets-Initiative/wireshark-lua/files/4725352/iLink3DissectorErrors.zip)

**Comment by Open-Markets-Initiative** [comment]
Thanks.  It look like there are fields with different sizes in different messages.  I need to update the sbe loader since there are conflicting types.

**Comment by Open-Markets-Initiative** [comment]
Composite types had a conflict.  Please see latest commit: https://github.com/Open-Markets-Initiative/wireshark-lua/commit/9b1ee8b23a2e8f788e032db28ebc93d19484e84d
