### ISSUE TITLE
Request: generate lua for Eurex EMDI T7 8.0

### ISSUE THREAD

**Issue by nlee39** [Open-Markets-Initiative/wireshark-lua#21]
[Emdi.10000.pcap.zip](https://github.com/Open-Markets-Initiative/wireshark-lua/files/5144219/Emdi.10000.pcap.zip)

**Comment by Open-Markets-Initiative** [comment]
Thanks, I found some example parsers and this will require a separate generation path.  I will start on it but it might be some time.

**Comment by Open-Markets-Initiative** [comment]
We started on a separate generation model for FAST, but it will be a while before we are able to successfully generate these types of protocols.  I am closing this for now since we are not going to add this functionality in the near term.
