### ISSUE TITLE
Request: generate lua for new ASX24 New Trading Platform 'NTP'

### ISSUE THREAD

**Issue by edmaher** [Open-Markets-Initiative/wireshark-lua#22]
This is probably a minimal change to the legacy ASX24 for the ITCH protocol

docs
https://www.asxonline.com/public/landing-pages/ntp-document-library.html#protocol

**Comment by Open-Markets-Initiative** [comment]
We are refactoring part of the compiler, we will get to this shortly.  Any chance you have a pcap?

**Comment by edmaher** [comment]
yes, I'll get one sorted.

**Comment by Open-Markets-Initiative** [comment]
Working on this tonight, should have a dissector soon.  Were you able to locate a pcap?

**Comment by edmaher** [comment]
[sfe-channel-233-71-185-65--100kpkts.pcap.gz](https://github.com/Open-Markets-Initiative/wireshark-lua/files/5620828/sfe-channel-233-71-185-65--100kpkts.pcap.gz)

Try this one

**Comment by edmaher** [comment]
let me know if you need more/different sample, or a glance stream

**Comment by Open-Markets-Initiative** [comment]
Ntp dissector was added in https://github.com/Open-Markets-Initiative/wireshark-lua/commit/e03cc9c6a9ad8866bdeede7a275a8bf83211dfb8 ... it has been tested and should mostly work but needs some polish on enums and possibly repeating structures could be handled more elegantly.  We will update and regenerate soon.

If you have a glance pcap, please send it our way...we dont have any examples of these itch style tcp snapshots and could use that to generate the protocols together.
