### ISSUE TITLE
Deprecated link

### ISSUE THREAD

**Issue by mariov652** [Open-Markets-Initiative/wireshark-lua#23]
Hello,

Not very importantl, but I thought I would just mention the link in the readme files referring to Wireshark LUA documentation lead to a now-deprecated link: https://wiki.wireshark.org/Lua.

This has been migrated to: https://gitlab.com/wireshark/wireshark/-/wikis/home.

However, a search here, leads to : https://gitlab.com/wireshark/wireshark/-/wikis/LuaAPI, which ultimately leads to this final link for LUA documentation: https://www.wireshark.org/docs/wsdg_html_chunked/wsluarm_modules.html

Regards,

**Comment by Open-Markets-Initiative** [comment]
Thanks.  All fixed.
