### ISSUE TITLE
custom SBE dissector code generator

### ISSUE THREAD

**Issue by thetoothpick** [Open-Markets-Initiative/wireshark-lua#26]
Hello!

My team is interested in generating wireshark dissectors for our custom SBE messages - we came across your project and wanted to see if it would be possible to use / reference your generators.  I've seen issues #5 and #9 - is releasing the source code still in your plans?

Some of our work might also be interesting to you - if you have an email I can contact I'd be happy to discuss our use-case in more detail.

Thanks!

Kevin Arthur

**Comment by Open-Markets-Initiative** [comment]
Thanks for reaching out.  We are currently preparing some of the core compiler platform libraries for for release (its important to keep the pace of development) but our time frame is probably different that yours, so well work out some kind of loan.
