### ISSUE TITLE
ICE Impact protocol

### ISSUE THREAD

**Issue by CTurner22** [Open-Markets-Initiative/wireshark-lua#27]
The newer ICE iMpact protocol has broken the 1.1.34 dissector by adding field and changing offsets in multiple different types of packets. Could the ICE iMpact protocol be regenerated for the current 1.1.43 version of the protocol?

**Comment by Open-Markets-Initiative** [comment]
If you could post the pdf spec to this ticket, we will add the new version. Also, if you have a small pcap that would help.

**Comment by CTurner22** [comment]
Hi, I have attached the pdf spec but am unable to provide a pcap. While I
can't provide the actual data, I can perform tests if needed.

Thanks

**Comment by Open-Markets-Initiative** [comment]
I dont see the spec...maybe the replay by mail did not work.

**Comment by CTurner22** [comment]
[ICE_iMpact_Multicast_Feed_Message_Spec_1.1.43.pdf](https://github.com/Open-Markets-Initiative/wireshark-lua/files/6718596/ICE_iMpact_Multicast_Feed_Message_Spec_1.1.43.pdf)

**Comment by Open-Markets-Initiative** [comment]
I am almost done with the updates.  I took this opportunity to rebuild the iMpact loader.  In the future, if you post every new mdf spec or once every few I can make updates from the change list (instead of a full comparison) and regenerate quickly.

**Comment by Open-Markets-Initiative** [comment]
First round:

https://github.com/Open-Markets-Initiative/wireshark-lua/commit/a2c731019e0cd7042a9c505f6eaf7a76c3711299

This version contains the message skeleton. Enums, bitfields and some rules will be updated once we finish updating the loader.

**Comment by CTurner22** [comment]
Thanks, really appreciate your response and quick update. I'll be sure to test the Beta this week and let you know.

**Comment by Open-Markets-Initiative** [comment]
Please clone again and test with:

https://github.com/Open-Markets-Initiative/wireshark-lua/commit/9bdbf738c4afb8e8ebf7b4c90086a9745895dfcc

I made a mistake and generated from the wrong precursor files.

**Comment by CTurner22** [comment]
Sounds good, I'll pull the new one.

**Comment by Open-Markets-Initiative** [comment]
Full version at:

https://github.com/Open-Markets-Initiative/wireshark-lua/commit/99ea0f376c84a6831e3779b605ce875b9c3c42ee

Please let me know if you see any issues
