### ISSUE TITLE
cme_futures_ilink3_sbe_v8_7 testing

### ISSUE THREAD

**Issue by youknowwhoitis** [Open-Markets-Initiative/wireshark-lua#28]
Hey,

First of all, thank you for the hard work involved in creating these dissectors and making our lives easier in the process.

This is a non-issue really, just an fyi that I have tested with production captures the CME Futures SBE dissector and there are no errors found in the last packets I have analysed.

https://postimg.cc/GHc06W0Q

I can send you some production captures containing some new orders, heartbeats and execution reports if needed, I just need to know what's the email address.

**Comment by Open-Markets-Initiative** [comment]
Thanks, we work with a couple of firms on CME protocols so we have the order entry mostly covered.  Since you are offering though...

What other exchanges do you have data for?
Do you have a packet with message 561 in iLink3?

**Comment by youknowwhoitis** [comment]
(rolls sleeves)

What are you guys after?

Some that come to mind are:

   - Fastmatch ITCH
   - Gain GTTP
   - Currenex OUCH and ITCH
   - Hotspot ITCH
   - Eurex (I am not sure yet what protocol they use, I'll have to check)

For message 561 I can't find any occurrence in the previous capture that
I've taken when I sent this email, I'll take a new one and come back to
you. Message 561 would be SecurityDefinitionResponse

**Comment by Open-Markets-Initiative** [comment]
We have not previously heard of several of the listed protocols but these definitely fall under our purview.  Can example captures be acquired for these protocols?

We should figure out some way to communicate outside of github,.

**Comment by youknowwhoitis** [comment]
Sure thing, I'll take some captures today and send them over, let me know
your email address and I can send them over and continue the communication
there.

**Comment by Open-Markets-Initiative** [comment]
omi.development at protonmail.com
