### ISSUE TITLE
Using TotalView Itch 5.0 Dissectors

### ISSUE THREAD

**Issue by justinjabate** [Open-Markets-Initiative/wireshark-lua#29]
I'm trying to use:
- Nasdaq.Bx.Equities.TotalView.Itch.v5.0.Script.Dissector.lua
- Nasdaq.Equities.TotalView.Itch.v5.0.Script.Dissector.lua
- Nasdaq.Psx.TotalView.Itch.v5.0.Script.Dissector.lua

With the respective PCAPs from ftp://emi.nasdaq.com/ITCH/
{BX_ITCH_50, NASDAQ_ITCH50, PSX_ITCH_50}

Opening as such:
![image](https://user-images.githubusercontent.com/18313961/124317638-7bbad400-db45-11eb-832f-8ba7faca389f.png)

But I receive errors like this:
![image](https://user-images.githubusercontent.com/18313961/124317751-ab69dc00-db45-11eb-95e6-ab5a6f7df025.png)

Is there something I'm missing?

**Comment by Open-Markets-Initiative** [comment]
Can you please post example pcaps here as we do do not have access to that ftp site

**Comment by justinjabate** [comment]
They're too large to post in the comment so I've uploaded here:
https://www.mediafire.com/folder/w8ovegtr8prnm/ITCH_50

**Comment by Open-Markets-Initiative** [comment]
I dont think these files are pcaps.  Nasdaq probably could tell you more but I believe them to be some proprietary data format produced by Nasdaq. However, I once came across another project that used these files:

https://github.com/DavZim/RITCH
