### ISSUE TITLE
Can you generate a new dissector for the BOE v2 protocol? (BATS/CBOE)

### ISSUE THREAD

**Issue by mrossi19** [Open-Markets-Initiative/wireshark-lua#3]
http://cdn.batstrading.com/resources/membership/US_Options_BOE_Specification.pdf

Thanks.

**Comment by Open-Markets-Initiative** [comment]
Bats Boe is on the docket.  

Protocols where we lack expereince are hard to get right without something to dissect.  Can you provide a sample? Also, this is a large protocol (actually 3 or 4) with alot of brnaches, it may take a few iterations to fully capture every detail.   

What is your time frame?

**Comment by rweiss42** [comment]
Just wondering if there's been any progress on a BOE dissector.  Are you still in need of sample data?

**Comment by Open-Markets-Initiative** [comment]
We are currently upgrading the back end to handle multiple transport layers concurrently.  After that, Boe and Eti are the top of the list.  

Once we compose a boe loader we will start testing boe.  Note that boe has some unique characteristics and it migght take a few iterations.  We are still in need of current sample data...our tests were going to be run on the samples from:

https://github.com/BATS/bats-dissectors

But these are 5 years old. Thanks for your interest.

**Comment by Open-Markets-Initiative** [comment]
We are upgrading the backend to handle multiple transport layers concurrently. After that Boe and Eti are the top of the list.

Once we get a Boe loader up and running we will start testing.  Current data would be great.  Our only example is from:

https://github.com/BATS/bats-dissectors

And that's 5 years old.  Note that boe has some unique properties and it may take a few iterations.  Thanks for your interest.  Go Maroons.

**Comment by Open-Markets-Initiative** [comment]
Beta version of BOE options up at: https://github.com/Open-Markets-Initiative/wireshark-lua/commit/3f6a400032454b067fcc4dee5e686ba74998548c

Notes:  
- some optional rpeating groups will not likely work
- old protocol test data was not exact 
- plans are to split protocol family (C1/C2/EGX/BZX) and do equities
- probably can make bitfields less message dependent
