### ISSUE TITLE
Support of CME MDP Conflated Transmission Control Protocol (TCP) for EBS Market on CME Globex

### ISSUE THREAD

**Issue by rasenschachmatt** [Open-Markets-Initiative/wireshark-lua#31]
Support of the latest SBE schema for [CME MDP Conflated User Datagram Protocol (UDP)](https://www.cmegroup.com/confluence/display/EPICSANDBOX/CME+Globex+EBS+Market+-+Market+Data#CMEGlobexEBSMarketMarketData-CMEMDPConflatedUserDatagramProtocol(UDP)) has been added with issue #30.

In order to add full support for [EBS Market on CME Globex](https://www.cmegroup.com/confluence/display/EPICSANDBOX/EBS+Market+Integration+onto+CME+Globex), the [CME MDP Conflated Transmission Control Protocol (TCP)](https://www.cmegroup.com/confluence/display/EPICSANDBOX/CME+Globex+EBS+Market+-+Market+Data#CMEGlobexEBSMarketMarketData-CMEMDPConflatedTransmissionControlProtocol(TCP)) should be supported in a dedicated Omi Lua Wireshark dissector script.

This dissector script should combine
- TCP protocol
- [SBE Technical Header for TCP Conflated Connections](https://www.cmegroup.com/confluence/display/EPICSANDBOX/CME+Globex+EBS+Market+-+Market+Data+Message+Specification#CMEGlobexEBSMarketMarketDataMessageSpecification-SBETechnicalHeaderforTCPConflatedConnections)
- MDP SBE message schemas
  - [templates_FixBinary_v12.xml](https://www.cmegroup.com/ftp/SBEFix/NRCert/Templates/templates_FixBinary_v12.xml) already available in [directory](https://github.com/Open-Markets-Initiative/Directory/blob/main/Specifications/Cme/Cme.Futures.Mdp3.Sbe.v1.12.xml)
  - [templates_MdpSessionMgmt_v0.xml](https://www.cmegroup.com/ftp/SBEFix/NRCert/SessionManagement/Templates/templates_MdpSessionMgmt_v0.xml)

It would be great if you could support this in Open Markets Initiative!

**Comment by rasenschachmatt** [comment]
Hi, I need some time to get a pcap for TCP, but I hope I can provide one within a week or so.

**Comment by Open-Markets-Initiative** [comment]
Sounds good.  I think it will be hard to get this right without a pcap.

**Comment by Open-Markets-Initiative** [comment]
Any luck acquiring that pcap?

**Comment by rasenschachmatt** [comment]
Sorry for the delay.

Please find a pcap for CME MDP Conflated TCP in the archive below:
[CME.MDP3.SBE.V1.12.TCP.zip](https://github.com/Open-Markets-Initiative/wireshark-lua/files/7134887/CME.MDP3.SBE.V1.12.TCP.zip)

**Comment by Open-Markets-Initiative** [comment]
Thanks give me a couple of days.

**Comment by Open-Markets-Initiative** [comment]
Please try this:
[Cme.Futures.Mdp3.Sbe.v1.12.Script.Dissector.txt](https://github.com/Open-Markets-Initiative/wireshark-lua/files/7188229/Cme.Futures.Mdp3.Sbe.v1.12.Script.Dissector.txt)

change to .lua

**Comment by rasenschachmatt** [comment]
Thanks for the dissector script. It generally looks good and the data seems plausible.

However, I observed some artifacts when applying it to the pcap above. You can see these anomalies in frame 4 and 173 of the pcap:

![frame4](https://user-images.githubusercontent.com/19908919/133922448-6f137574-75c3-4f4a-ae64-7f56ebd3eca4.png)

![frame173](https://user-images.githubusercontent.com/19908919/133922465-c5d398d2-3df0-4ad2-8e5c-2ff1e4e849ec.png)

The first message (marked in green) looks good, but after this, there are more messages displayed with strange message sizes (marked in red).

Do you have any idea where these artifacts might come from?

**Comment by Open-Markets-Initiative** [comment]
Frame 4 looks like some inconsistency between the on wire fields and the CME's SBE xml.  For instance, its likely FxCurrencySymbol is correct at EUR/USD.  Furthermore, several of the repeating groups after this value report likely correct group values (MdFeedType: GBX).  However, TradingSessionGroup has block length of 16960.  At some point before this, the dissector has likely come off the rails.

**Comment by Open-Markets-Initiative** [comment]
If you have a UDP pcap, I can use it to test the use dissector to see if there are any similar inconsistencies.
