### ISSUE TITLE
Nasdaq ITTO Has incoreect Price and Volume Widths

### ISSUE THREAD

**Issue by mtoner23** [Open-Markets-Initiative/wireshark-lua#32]
On nasdaq nom ITTO feed all of the Long Form message variants encode the price and volume fields as 4 byte values. The dissectors here do not differentiate between long and short form price and volumes and long form so all messages are encoded with short price and volume.

Check the Add Order Message Long form here
http://www.nasdaqtrader.com/content/productsservices/trading/optionsmarket/itto_spec40.pdf

**Comment by Open-Markets-Initiative** [comment]
Thanks, We will post a fix shortly.  Any change you can post a pcap with the error?

**Comment by Open-Markets-Initiative** [comment]
Please see commit: https://github.com/Open-Markets-Initiative/wireshark-lua/commit/b513bd92cc1a8bd7ffcae4dcf602ca17aca63962
