### ISSUE TITLE
Cme.Futures.Derived.Sbe.v12.0.Script.Dissector.lua Error:1734: Range is out of bounds.

### ISSUE THREAD

**Issue by MarketDataUser** [Open-Markets-Initiative/wireshark-lua#33]
Hello there.

I'm quite impressed by your work. thanks for sharing.
I've tried your CME-v12 dissector and got "Range is out of bounds" errors (line 1734 and 1699)
I've uploaded a small cap with 50 packets.
Let me know how I can help.
regards,

[CME-v12.pcap.zip](https://github.com/Open-Markets-Initiative/wireshark-lua/files/7520375/CME-v12.pcap.zip)
)

**Comment by MarketDataUser** [comment]
oooppps wrong plugin.... sorry.

**Comment by Open-Markets-Initiative** [comment]
You are welcome
