### ISSUE TITLE
OUCH 4.2 Enter Order field "Customer Type" field is optional

### ISSUE THREAD

**Issue by selavy** [Open-Markets-Initiative/wireshark-lua#35]
The "Customer Type" field in OUCH 4.2 is an optional field on the "Enter Order" message, which causes [`size_of.enter_order_message`](https://github.com/Open-Markets-Initiative/wireshark-lua/blob/3d9c908726e646faff83640e4a6c52b2de38fa18/Nasdaq/Nasdaq.Equities.Orders.Ouch.v4.2.Script.Dissector.lua#L2154) to return the wrong value.

spec: http://www.nasdaqtrader.com/content/technicalsupport/specifications/tradingproducts/ouch4.2.pdf

![image](https://user-images.githubusercontent.com/4603105/147698730-f3e3115e-fe5a-4a50-82f6-38037cdfb734.png)

**Comment by Open-Markets-Initiative** [comment]
Thank you for pointing this out, please see: 4bb8e527cf770f4be5e91aaeb68547b85cd40b64
