### ISSUE TITLE
release the generator code?

### ISSUE THREAD

**Issue by mbruce** [Open-Markets-Initiative/wireshark-lua#36]
I am looking at building parsers in rust.  would you be willing to release the generator so I could leverage your platform to build many parsers quickly?

**Comment by Open-Markets-Initiative** [comment]
We are looking to open up the platform but it will have to wait until we finish a couple flavors of C++ and Java code. The engines and the domain specific languages are not ready for certain types of expansion. However, if you have source code models and easy ways to test, we might be able to work together get something up and running for rust.

**Comment by mbruce** [comment]
would you be able to open up the feed definitions (assuming you have a way to describe, say, the utp feed generically)?  or is this baked in to the platform's code?

**Comment by Open-Markets-Initiative** [comment]
What exactly do you mean open up the feed definitions?   In a case like UTP, our platform parses the specifications directly from the pdf elements.  That intermediate info is like a normalized specification.  These are compiled into protocol/data models.  Then after that we have source generation.

**Comment by hnspn** [comment]
> our platform parses the specifications directly from the pdf elements.  

wow

How can you make pdf parsing robust? it's not like all the exchanges have a standard pdf layout

**Comment by Open-Markets-Initiative** [comment]
It takes 2 components.  

1) the ability read many different formats (source gen is useful here also
2) An 'edit' domain specific language for when you read too much (or too little) information

The fastest way to get Rust parsers up and running is to provide us with a code model and some way to test
