### ISSUE TITLE
Support for Cboe MarketData Pitch v2.41.29 and Complex MarketData Pitch v2.1.37

### ISSUE THREAD

**Issue by baumgold** [Open-Markets-Initiative/wireshark-lua#38]
The current version of the Cboe MarketData dissector is based on the Cboe PITCH spec v2.39.4 from August 2018. Since then Cboe has upgraded to v2.41.29. The current dissector is not compatible with the new protocols:

https://cdn.cboe.com/resources/membership/US_EQUITIES_OPTIONS_MULTICAST_PITCH_SPECIFICATION.pdf
https://cdn.cboe.com/resources/membership/US_OPTIONS_COMPLEX_MULTICAST_PITCH_SPECIFICATION.pdf

Could you please generate a Wireshark dissector script for Cboe Equity/Options MarketData v2.41.29 and Cboe Options Complex MarketData v2.1.37? This is applicable to Options and Equity exchanges (Bzx-Equities, Edgx-Equities, Bzx-Options, Edgx-Options, C1-Options). Thanks!

**Comment by Open-Markets-Initiative** [comment]
Thanks for posting, usually we can respond quickly but several of us are on vacation through mid-august.  we will post these requests shortly after that.

**Comment by Open-Markets-Initiative** [comment]
Complex options updates included in: https://github.com/Open-Markets-Initiative/wireshark-lua/commit/db87d4b5459bc82ed509b4458e777ed82b276f20

(note older dissector has not changed much and should work)

**Comment by Open-Markets-Initiative** [comment]
Market depth added for equities and options over last few commits.  If you have any pcaps for testing, please let us know.
