### ISSUE TITLE
NYSE Pillar for Options

### ISSUE THREAD

**Issue by etobis** [Open-Markets-Initiative/wireshark-lua#39]
Hi!

Can I help you add support for that protocol? ARCA has now fully migrated to that platform.

Thanks!

**Comment by Open-Markets-Initiative** [comment]
Last protocol added in: https://github.com/Open-Markets-Initiative/wireshark-lua/commit/414af525b57a49b77deec39db1da973fa8a62cd1

**Comment by etobis** [comment]
Thank you! This seems to cover the market data feed. Any chance I can help you add the protocol for orders and quotes?
