### ISSUE TITLE
Nasdaq OUCH 5.0 unable to decode

### ISSUE THREAD

**Issue by sbolberov** [Open-Markets-Initiative/wireshark-lua#43]
Lua Error: ...ns/Nasdaq.Equities.Orders.Ouch.v5.0.Script.Dissector.lua:4790: attempt to call field 'soup_bin_tcp_packet' (a nil value)

Using Wireshark 4.0.5 on Mac
[Corvil-58755-1683811800003940707-1683811860003940707-na-1_20000000__false_-ordernone-false-bidirectional.zip](https://github.com/Open-Markets-Initiative/wireshark-lua/files/11466505/Corvil-58755-1683811800003940707-1683811860003940707-na-1_20000000__false_-ordernone-false-bidirectional.zip)

The Pcap file is attached

**Comment by Open-Markets-Initiative** [comment]
Thanks for bringing this too our attention.  Updates shortly.

**Comment by Open-Markets-Initiative** [comment]
Updates in: https://github.com/Open-Markets-Initiative/wireshark-lua/commit/849133c9e0590456438726c80b499cd632432bc7
