### ISSUE TITLE
NYSE Pillar Gateway Binary Protocol

### ISSUE THREAD

**Issue by karljensen** [Open-Markets-Initiative/wireshark-lua#44]
Can a NYSE Pillar Gateway Binary Protocol dissector be generated?

Spec available here:
https://www.nyse.com/publicdocs/NYSE_Pillar_Gateway_Binary_Protocol_Specification.pdf

**Comment by Open-Markets-Initiative** [comment]
Working on options version it right now.  Please check back in a few days. A single non source identifiable packet would help.

**Comment by Open-Markets-Initiative** [comment]
Beta version up: fc[24b3a34c48af7f887616b68f1047099a614a35](https://github.com/Open-Markets-Initiative/wireshark-lua/commit/fc24b3a34c48af7f887616b68f1047099a614a35)

Enums and some rules are missing.  We dont have an example and so its unlikely to work.

**Comment by Open-Markets-Initiative** [comment]
Thanks for the pcap.  There are a couple of issues. First, the protocol model is incorrect around sequenced messages. Also the generator does not handle Lua not equals correctly.  We should have something soon.

**Comment by Open-Markets-Initiative** [comment]
We hacked the packet and found that these are 0x0240 messages whch is only in the equities specification:
https://www.nyse.com/publicdocs/NYSE_Pillar_Gateway_Binary_Protocol_Specification.pdf

We will update the common stream protocol and get to equities after we finish pillar options.

**Comment by Open-Markets-Initiative** [comment]
General equities Pillar Binary Gateway dissector up in: 022fea4c4bd53a89177470aa2f58aaad2841ab91.  Any other messages in a pcap would be great.
