### ISSUE TITLE
Improper parsing of OUCH protocol message type

### ISSUE THREAD

**Issue by chutzimir** [Open-Markets-Initiative/wireshark-lua#46]
The message_type parsing code JNX OUCH is not correctly parsing some sequenced packets.

For example, in JNX OUCH, `jnx_equities_pts_ouch_v1_11_size_of.data` does this:

```
  -- Size of Replace Order Message
  if message_type == "U" then
    return jnx_equities_pts_ouch_v1_11_size_of.replace_order_message(buffer, offset)
  end
```
followed a few lines later by
```
  -- Size of Order Replaced Message
  if message_type == "U" then
    return jnx_equities_pts_ouch_v1_11_size_of.order_replaced_message(buffer, offset)
  end
```

Obviously, the second `if` will never be reached.

The message type "U" is the same for sequenced and unsequenced packets, but their payload is very different. Therefore, the message type (sequenced or unsequenced) should be taken into account in addition to checking the `message_type` byte.

The same issue exists for Nasdaq OUCH.

**Comment by chutzimir** [comment]
If it is any help, I pushed manual modifications to the generated Lua dissectors to https://github.com/Japannext/wireshark-lua/commits/jnx-updates to demonstrate how this can work.

Specifically, this commit:
https://github.com/Open-Markets-Initiative/wireshark-lua/commit/b9b0b30a58f9400752314d5818505fffbfff28ab

**Comment by Open-Markets-Initiative** [comment]
I did not understand the Ouch packet level parsing rules.  Updates shortly. Thank you for pointing this out.

**Comment by Open-Markets-Initiative** [comment]
Please try the updates in: https://github.com/Open-Markets-Initiative/wireshark-lua/commit/4fb440ce99a94a7571da3e368d0b80442cff4b42

This updated ouch model should fix a few of the issues.  Space padding with be handled shortly.

**Comment by chutzimir** [comment]
> Please try the updates in: [4fb440c](https://github.com/Open-Markets-Initiative/wireshark-lua/commit/4fb440ce99a94a7571da3e368d0b80442cff4b42)
> 
> This updated Ouch model should fix a few of the issues. Space padding with be handled shortly.

Thank you. I can confirm that the JNX OUCH is correctly parsing the sequenced and unsequenced messages.

Also confirmed that the order tokens are displayed correctly.
