### ISSUE TITLE
B3 (Brazilian Exchange) Parsers

### ISSUE THREAD

**Issue by hilton-98** [Open-Markets-Initiative/wireshark-lua#48]
Could you add the WireShark plugins for the B3 Market Data parsers?

If so, these links might be useful,

B3 documentation for Market Data Feeds: https://clientes.b3.com.br/en_us/roadmap/about/binary-market-data.htm
XML file with B3 parser definitions: https://clientes.b3.com.br/data/files/E2/01/50/7C/286B8810C1C18788180808FF/b3-market-data-messages-1.6.0.xml

B3 updated their encoding to use SBE, and use a very similar protocol to the CME for their Market Data feeds.

**Comment by Open-Markets-Initiative** [comment]
Will do shortly.  Any chance you have a pcap? Because the headers are usually only partially defined we have never generated a sbe protocol correctly on the first try.

**Comment by hilton-98** [comment]
Great! B3 actually supplies some pcaps, at that same link. They have three different streams:
1. Incremental stream
2. Snapshot stream
3. Instrument definition stream


Pcaps for each can be found at the following links:
1. https://mktdatabinario.z15.web.core.windows.net/04042023_PCAPS/20220822_MBO_072_SnapshotRecovery.zip

**Comment by Open-Markets-Initiative** [comment]
Thanks for the links, I am testing the beta of the BinaryUmdf.  Should have something soon.

**Comment by hilton-98** [comment]
Fantastic! Thank you.

**Comment by Open-Markets-Initiative** [comment]
I thought I would be done by now, but this sbe xml is somewhat different around nulls.  I think another day or so.

**Comment by hilton-98** [comment]
Ok. Thanks for keeping me updated! That sounds good.

**Comment by Open-Markets-Initiative** [comment]
I have the BinaryUmdf  parsing but there is something strange in a few of the messages.  One of two things is likely, either the data doesn't match the xml or there is something I am reading incorrectly (some of the field sizes are different).  I am going to spend one more day on this and post for a second set of eys.

**Comment by Open-Markets-Initiative** [comment]
Probably needs more work but is likely mostly done:

https://github.com/Open-Markets-Initiative/wireshark-lua/commit/6de97106911149d164db46bbf27e01ed0ec7b586

**Comment by hilton-98** [comment]
Thank you! There are some problems with it still (I keep getting a "Range is out of bounds" error) but at least I can see some of the messages are decoding correctly in Wireshark. Sorry for the late response. I don't have any of the earlier versions, and I don't know where to find them. I only started looking into this exchange recently and haven't developed for it before.
