### ISSUE TITLE
[Question] Any technical details can we learn?

### ISSUE THREAD

**Issue by tan-wei** [Open-Markets-Initiative/wireshark-lua#5]
Feel interesting about how these `lua` files being generated. So can I know some details about it?
Thanks a lot! Hope you have a nice weekend.

**Comment by Open-Markets-Initiative** [comment]
Hello, thanks for your interest in our project.   In the not too distant future, we will post some compiler examples and give a presentation on our source generation methods.  At the moment our protocol compiler is in development and not as complete as the lua dissector outputs stored in this repo.  We primarily post these dissectors for external testing and on going feedback.

In the meantime, if you are interested specifically in wireshark source generation:

https://gitlab.com/realrichardsharpe/wireshark-generator

http://protomatics.com/wireshark_dissector.html

If you are looking for financial protocol source generation, the best input/output example can be found here:

https://www.eurexchange.com/exchange-en/technology/t7/system-documentation

All you need to do is consume the provided xmls.

**Comment by tan-wei** [comment]
Thanks for your kind and detail reply. I will add this project in my watch list.
