### ISSUE TITLE
Wireshark switching to Lua 5.4

### ISSUE THREAD

**Issue by geraldcombs** [Open-Markets-Initiative/wireshark-lua#52]
Hi all, I know this isn't an issue per se, but the next major release of Wireshark will [switch to Lua 5.4](https://gitlab.com/wireshark/wireshark/-/blob/master/doc/release-notes.adoc). The release isn't currently scheduled, but will likely happen in the second half of this year. If you would like to test any Lua dissectors you can do so by downloading any of the 4.3.0rc0 development packages at https://www.wireshark.org/download/automated/. If you run into any issues, feel free to [open an issue](https://gitlab.com/wireshark/wireshark/-/issues), the [wireshark-dev mailing list](https://www.wireshark.org/lists/), or the Lua channel on our Discord server (sorry, you'll have to DM me for an invite link).

**Comment by Open-Markets-Initiative** [comment]
Thanks for reaching out.  We are currently focused on adding python to the Omi but I will see if we can run a test.

**Comment by Open-Markets-Initiative** [comment]
I pulled version Wireshark-4.3.0rc0-1850-gab5c10662a65-x64 and loaded a few dissectors.  Everything ran fine.  Thanks for showing me the issues....I have a few requests.

**Comment by crucio55** [comment]
At least multiple dissectors from this repository stopped loading for me when updating to wireshark's new 4.4.0 version (the ones I tried - `Nasdaq_Equities_Orders_Ouch_v5_0_Dissector.lua`, `Nyse_Options_StreamProtocol_Pillar_v1_6_Dissector.lua`, `Nyse_Arca_Options_BinaryGateway_Pillar_v3_15_Dissector.lua`) - no error message, they're just missing.

In the [release notes](https://www.wireshark.org/docs/relnotes/wireshark-4.4.0.html#:~:text=Plugins%20should%20provide%20a%20plugin_describe(),used.%20See%20wsutil%2Fplugins.h%20for%20details.), it's mentioned that plugins should now provide a `plugin_describe()` function - so either that, or the deprecation of Lua 5.1 and 5.2 versions could be the reason.

Can anybody else still successfully load dissectors into wireshark 4.4.0?
