### ISSUE TITLE
Nasdaq OUCH 5.0 unable to decode sequenced message

### ISSUE THREAD

**Issue by Huynhs** [Open-Markets-Initiative/wireshark-lua#53]
Wireshark versions used: 2.6.5 and 4.2.4 on windows and linux

This issue seems to occur to both sequenced and unsequenced messages, I don't see any implementation for sequenced_message in the script

Nasdaq Equities Orders Ouch 5.0 (21 Bytes)
Lua Error: ...ns\Nasdaq.Equities.Orders.Ouch.v5.0.Script.Dissector.lua:383: attempt to call field 'sequenced_message' (a nil value)
Lua Traceback
    stack traceback:
     ...ns\Nasdaq.Equities.Orders.Ouch.v5.0.Script.Dissector.lua:383: in function 'sequenced_data_packet_fields'
     ...ns\Nasdaq.Equities.Orders.Ouch.v5.0.Script.Dissector.lua:400: in function <...ns\Nasdaq.Equities.Orders.Ouch.v5.0.Script.Dissector.lua:389>
     (...tail calls...)
     ...ns\Nasdaq.Equities.Orders.Ouch.v5.0.Script.Dissector.lua:815: in function 'soup_bin_tcp_packet_fields'
     ...ns\Nasdaq.Equities.Orders.Ouch.v5.0.Script.Dissector.lua:829: in function 'soup_bin_tcp_packet'
     ...ns\Nasdaq.Equities.Orders.Ouch.v5.0.Script.Dissector.lua:869: in function <...ns\Nasdaq.Equities.Orders.Ouch.v5.0.Script.Dissector.lua:856>
     (...tail calls...)

Relevant pcap
[nasd-ouch-5.zip](https://github.com/Open-Markets-Initiative/wireshark-lua/files/15168828/nasd-ouch-5.zip)

**Comment by Open-Markets-Initiative** [comment]
It seems we upgraded the ouch normalizer but not all of the documents.  Updates shortly.  Thanks for the example capture.

**Comment by Open-Markets-Initiative** [comment]
I regenerated the SoupBinTcp header dissector.  I should have updates for the Ouch dissector sometime tomorrow.

**Comment by Open-Markets-Initiative** [comment]
Updated Nasdaq Ouch v5.0 Dissector: 947a9a0a0b19903614fb410bedde1b2feaa81ffd
