### ISSUE TITLE
CBOE Pitch Decimal Precision Number Transaltion

### ISSUE THREAD

**Issue by HotGiardiniera** [Open-Markets-Initiative/wireshark-lua#58]
[This commit](https://github.com/Open-Markets-Initiative/wireshark-lua/commit/d64c0235c80eceb178c4cbbf94c3a2bf816261a4) introduced Pitch Protocol with decimal precision. I believe the translation of these prices [(example)](https://github.com/Open-Markets-Initiative/wireshark-lua/commit/d64c0235c80eceb178c4cbbf94c3a2bf816261a4#diff-eafda39f5d90f0c6f6f3d11d8797e483cac66686c381508aa1a34b89a2bd3be2R1137) multiplies by a factor of X when it should divide.

For example:
in Futures DoB Pitch I am seeing a short price of `b4 00` which is displayed as 18000. The spec calls for Binary Short Price with 2 implied decimal places (denominator=100) so I would expect to see 1.8 here

**Comment by Open-Markets-Initiative** [comment]
Thanks for pointing this out.  The great beauty of source generation is that one can get it wrong everywhere.  Updates in: 99d668b42dfa2312ac6b3c07d8adfb3493d28dae

**Comment by HotGiardiniera** [comment]
Awesome thanks. Really appreciate your work
