### ISSUE TITLE
Nyse National display string incorrect

### ISSUE THREAD

**Issue by bkulback** [Open-Markets-Initiative/wireshark-lua#6]
Value 10 for  "Nyse Equities IntegratedFeed Xdp 2.1.g Protocol" should represent Equities, not Options [Reference https://www.nyse.com/publicdocs/nyse/data/XDP_Common_Client_Specification_v2.1f.pdf].  This is line 3226 of the generated LUA.

Should read "Market Id: Nyse National Equities (10)"

**Comment by Open-Markets-Initiative** [comment]
Thanks.  I'll have a look and regenerate.

**Comment by Open-Markets-Initiative** [comment]
All fixed. Thanks for your help and please let me know if you see anything else.
