### ISSUE TITLE
At least multiple dissectors from this repository stopped loading for me when updating to wireshark's new 4.4.0 version

### ISSUE THREAD

**Issue by Open-Markets-Initiative** [Open-Markets-Initiative/wireshark-lua#63]
At least multiple dissectors from this repository stopped loading for me when updating to wireshark's new 4.4.0 version (the ones I tried - `Nasdaq_Equities_Orders_Ouch_v5_0_Dissector.lua`, `Nyse_Options_StreamProtocol_Pillar_v1_6_Dissector.lua`, `Nyse_Arca_Options_BinaryGateway_Pillar_v3_15_Dissector.lua`) - no error message, they're just missing.

In the [release notes](https://www.wireshark.org/docs/relnotes/wireshark-4.4.0.html#:~:text=Plugins%20should%20provide%20a%20plugin_describe(),used.%20See%20wsutil%2Fplugins.h%20for%20details.), it's mentioned that plugins should now provide a `plugin_describe()` function - so either that, or the deprecation of Lua 5.1 and 5.2 versions could be the reason.

Can anybody else still successfully load dissectors into wireshark 4.4.0?

_Originally posted by @crucio55 in https://github.com/Open-Markets-Initiative/wireshark-lua/issues/52#issuecomment-2449395228_

**Comment by Open-Markets-Initiative** [comment]
Thanks for bringing this to our attention.  Looking into it.  The missing protocols seem to be the tcp protocols (with reassembly?).

**Comment by Open-Markets-Initiative** [comment]
I installed wireshark 4.4.0 and was able to parse sample packets with these dissectors on Windows 11.  Can you provide more context?

**Comment by Open-Markets-Initiative** [comment]
Closing this ticket. Please let us know if you see any other issues.

**Comment by crucio55** [comment]
I figured out what went wrong - Manjaro's distributed Wireshark 4.4.0 version was compiled without lua support :facepalm: 

I re-installed wireshark from flatpak, and now the plugins load just fine!

So the ticket can indeed be closed, the issue was in my environment alone :pray:
