### ISSUE TITLE
Integrated Feed Execution "Printable Flag" is incorrect

### ISSUE THREAD

**Issue by bkulback** [Open-Markets-Initiative/wireshark-lua#7]
The generated file "Nyse.Equities.IntegratedFeed.Xdp.v2.1.g.Lua" specifies an uppercase 'o' as a valid value.  The conditional should be compared to a zero '0' to indicate the execution was not printed.  Currently, "Printable Flag: Unknown(0)" is incorrectly shown.

-- Display: Printable Flag
display.printable_flag = function(value)
  if value == O then
    return "Printable Flag: Not Printed (O)"
  end
  if value == 1 then
    return "Printable Flag: Printed (1)"
  end

  return "Printable Flag: Unknown("..value..")"
end

**Comment by Open-Markets-Initiative** [comment]
I regenerated with the fixed value. Please let us know if you see anything else. Thank you.
