### ISSUE TITLE
lua is too slow, can we generate c code

### ISSUE THREAD

**Issue by edmaher** [Open-Markets-Initiative/wireshark-lua#9]
The lua code is convenient, but is way too slow.
It would be great if the generator also produced a decoder in c
Maybe the generator code could be open sourced also ?

**Comment by Open-Markets-Initiative** [comment]
The generation platform will produce c decoders, but the final version of these is some way off.  The generator is still under development and not stable, once the kernel is in a good place we will open it up for others to use.

If speed is a problem you can skip the structs in the protocol options.  Our tests show that lua is around 8x slower than c when you do a linear dissection.
